### ISSUE TITLE
Donation Group Count is not correct

### ISSUE THREAD

**Issue by swanhtet1992** [MMAUG/flood-website#11]
scroll ဆွဲမှ count ကို ပေါင်းသွားတာကြီးက တစ်မျိုးကြီးပဲ... လောလောဆယ် ဖြုတ်ထားကြမလား...

**Comment by greenlikeorange** [comment]
ဟုတ်တယ် ဖြုတ်မလို့ဘဲ API version အသစ်ရပြီလားလို့ စောင့်နေတာ.

**Comment by swanhtet1992** [comment]
မနက်မှရမယ်တဲ့... လောလောဆယ် အိပ်ကုန်ကြပြီ... 😴😴😴😴

**Comment by greenlikeorange** [comment]
အိုကေလေ ဒါဆို ဖြုတ်ထားလိုက်မယ်

**Comment by greenlikeorange** [comment]
@swanhtet1992 @alt332 page count ရတောင်းလို့ရပြီလား

**Comment by swanhtet1992** [comment]
v2 နဲ့တစ်ခါတည်းလာလိမ့်မယ်... ခုရေးနေကြတယ် https://github.com/alt332/floodinfo-myanmar/

**Comment by greenlikeorange** [comment]
အခုမှန်သွားပါပြီ
