### ISSUE TITLE
Google Map Maker Design 

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#13]
![umaidjf__gdfyobectgo14nwrp88fgfqe4qjo703r9k5fh6dic2ny-o_jpxea1czgg4zy7ghu1crxolckqjldynfl-tbntcsxzdm7nx1-bivp01txiy](https://cloud.githubusercontent.com/assets/4847843/9028047/a8b0091e-3991-11e5-88a4-9130123f876b.png)

Can we do like this?

**Comment by dreamingblackcat** [comment]
OK let me try today bro.

**Comment by greenlikeorange** [comment]
I think current one is good enough.
