### ISSUE TITLE
Make Automatic build system with bundle 

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#24]
Currently we use `npm` + `bundle`, it look like confuse. And also we are always pushing generated context which should ignore every time.
So far I don't know package management system at ruby, Can someone please help us to make automatic build system with gulp.

That make scene? 

@yelinaung @swanhtet1992 @dreamingblackcat @nyanlynnhtut @DragonVirus

**Comment by swanhtet1992** [comment]
I have no idea about this ruby thing. :disappointed:

**Comment by greenlikeorange** [comment]
@swanhtet1992 Sorry for attach you :D

**Comment by yelinaung** [comment]
It's not the `bundle` that needs the work. Bundler is just a dependency manager. It should be something like `Rake` which does the takes. Let me investigate an option I have in my mind and get back to you.

**Comment by yelinaung** [comment]
@greenlikeorange So, what you want is just automated asset compilation during the deployment ?

**Comment by greenlikeorange** [comment]
@yelinaung I want to add genetared content to .gitignore and they will generate duing build at heroku. Somethink like that.

**Comment by yelinaung** [comment]
@greenlikeorange Yes. That's what I just said.

**Comment by greenlikeorange** [comment]
Yes. How can we do. Can you help us? Please.

**Comment by yelinaung** [comment]
Or do you think node can do the thing ? does express.js or something has the compilation process before deployment ?

**Comment by greenlikeorange** [comment]
Yes node support full process. If server will not down for long time let change node stuff

**Comment by yelinaung** [comment]
Yup. Only about less than 50 users are online for a while. So, it's fine for me to down for a while.

**Comment by greenlikeorange** [comment]
Ok i will do that quick and notifiy u asps

**Comment by yelinaung** [comment]
@greenlikeorange Cloudflare has an option called "Auto Minify". Do you think we should try that one too ? If you're already working on the js version, then nevermind that

**Comment by greenlikeorange** [comment]
@yelinaung yes please, that is good option

**Comment by greenlikeorange** [comment]
I also working on node version too.

**Comment by greenlikeorange** [comment]
Now project is working node-stuff with `npm`, Cheer.!
