### ISSUE TITLE
Security ISSUS

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#26]
ကျွန်တော်တို့ API ကရော် Client မှာပါ html tags တွေကာရပါမယ်။
ကျွန်တော် အခု `$.http` ကနေဝင်လာသမျှ tags တွေအကုန်လုံးကို ဖြုတ်ထားပါတယ်။ ဘာလိုလဲဆိုတော့ Donation က `showDetailBox` မှာ `html` တွေကို ပြန်ကာထားတာမျိုး မထားထားပါဘူး ပြီးတော့ description တွေကိုလဲ ကျွန်တော်ကိုယ်တို့် `v-html` ကိုသုံးထားပါလို့ပါ။

ဒီထက်ပို်ကောင်းမဲ့ ဟာများရှိအုံးမလား?

@nyanlynnhtut @DragonVirus @dreamingblackcat

**Comment by dreamingblackcat** [comment]
Server side က Escape လုပ်ပေးရုံနဲ့　အဆင်မပြေဘူးလား။

**Comment by greenlikeorange** [comment]
I think it enough for now!
