### ISSUE TITLE
Design Broken at news

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#3]
![screen shot 2015-08-02 at 17 31 03](https://cloud.githubusercontent.com/assets/4847843/9025822/56c888a6-393c-11e5-9ade-84d4630dbd75.png)

It was broken since #5055ca7cc804bd82730b5435bb6e37f687e1b238 commit, I don't know why that is happened. Please check.

**Comment by nyanlynnhtut** [comment]
Already fixed.

**Comment by greenlikeorange** [comment]
:red_circle: Site is total broken again

**Comment by DragonVirus** [comment]
@greenlikeorange seem like u accidentally delete } from mdl minify css .. :D Fixed it.

**Comment by greenlikeorange** [comment]
@DragonVirus Cool, I just report :dancers:
