### ISSUE TITLE
Vuejs to Angular

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#34]
Hey let change that.
Check List
- [x] Landing Page
- [x] News Page
- [x] News and Donation Forms
- [x] Map Page
- [x] Campaigns Page
- [x] About Page

**Comment by nyanlynnhtut** [comment]
@greenlikeorange How about design? Bcoz, https://material.angularjs.org/latest/ 
:smile:

**Comment by greenlikeorange** [comment]
Do you want to change?

**Comment by nyanlynnhtut** [comment]
@greenlikeorange I am confuse

**Comment by greenlikeorange** [comment]
I mean do you want to use these stylesheets in new version with angular.

**Comment by nyanlynnhtut** [comment]
@greenlikeorange Ok. We will used angurlarjs only. Not material angular

**Comment by greenlikeorange** [comment]
@nyanlynnhtut I added checklist !! Which pages you will do and which page i have to do :)

**Comment by greenlikeorange** [comment]
Done
