### ISSUE TITLE
What Font will use for Unicode?

### ISSUE THREAD

**Issue by greenlikeorange** [MMAUG/flood-website#5]
Let me guess tharlon?

**Comment by nyanlynnhtut** [comment]
Ping : @yelinaung @DragonVirus @swanhtet1992

**Comment by yelinaung** [comment]
TharLon from Google Web Font will do.

**Comment by swanhtet1992** [comment]
embed လုပ်လို့ရမယ့် အဆင်ပြေမယ့်ဟာသာသုံးကိုကြီး

**Comment by yelinaung** [comment]
I am sorry. My mind slipped on this one. Why Unicode ?

**Comment by greenlikeorange** [comment]
@yelinaung For keyword search, Unicode is great. Something like for ရခိုင် in zawgyi ရ ခ ု ိ င ္ or ရ ခ ိ ု င ္ both are see able but can't searchable. :3

**Comment by yelinaung** [comment]
@greenlikeorange Yes. I understand.
