### ISSUE TITLE
News Form not clear after submit

### ISSUE THREAD

**Issue by swanhtet1992** [MMAUG/flood-website#9]
Need to clear the news form after the submit.

**Comment by greenlikeorange** [comment]
Sorry, Please remove my **test** post, I reported that.

**Comment by swanhtet1992** [comment]
မရသေးဘူးလေ... @greenlikeorange

**Comment by greenlikeorange** [comment]
ဟင် ရသွားပီဟုတ်ဘူးလား ?

**Comment by swanhtet1992** [comment]
မရသေးဘူးဗျို့...

**Comment by greenlikeorange** [comment]
ဘယ်ရမလဲ ဘာမှမှမလုပ်ရသေးတာ :smile_cat:

**Comment by greenlikeorange** [comment]
ရှင်းပြီးပြီ
